name: iOS

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Version
      run: |
        NEW_VERSION="${GITHUB_REF#"refs/tags/"}"
        PREVIOUS_VERSION=`cat file.podspec | grep "s.version" | cut -d "=" -f2 | cut -d \" -f2`
        echo $PREVIOUS_VERSION
        sed -ie "s/\([[:space:]]*s\.version[[:space:]]*= \"\)${PREVIOUS_VERSION}/\1$NEW_VERSION/" file.podspec

        git config user.name "Boris Kalim"
        git config user.email "boris@minutemedia.com"

        git add file.podspec
        git commit -am "Bump version in file.podspec"

        git push
