name: iOS

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: REF
      run: |
        version = ${$GITHUB_REF#refs\/tags\/}
        echo "${version}"
